version: "2"
services:
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment: 
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    #build: .
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "events"
      POSTGRES_USER: "startdataengineer"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./dbsetup:/docker-entrypoint-initdb.d

  serverloggenerator:
    build: ./
    image: sde:1-FLINK-1.11-scala_2.11
    command: "java -classpath /opt/frauddetection.jar:/opt/flink/lib/* com.startdataengineering.ServerLogGenerator"
    depends_on:
      - kafka